name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  commitlint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: |
            - args: [--frozen-lockfile, --strict-peer-dependencies]
      - name: Install commitlint
        run: |
          pnpm install -w conventional-changelog-conventionalcommits
          pnpm install -w commitlint@latest

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: pnpm exec commitlint --last --verbose

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: pnpm exec commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: |
            - args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Build
        run: pnpm build

      - name: test
        run: pnpm test

      - name: 'Report Coverage'
        uses: davelosert/vitest-coverage-report-action@v2

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          file: coverage/cobertura-coverage.xml
          format: cobertura
          fail-on-error: true

  lint:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: |
            - args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Build
        run: pnpm build

      - name: lint
        run: pnpm lint

  bench:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: |
            - args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Build
        run: pnpm build

      - name: bench
        run: CI=true pnpm bench
